# Generated by Django 5.2 on 2026-08-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
