# Generated by Django 5.2 on 2026-08-19 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تماس باید به صورت 09123456789 باشد.",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("wholesale_cooperation", "درخواست همکاری عمده"),
                            ("price_inquiry", "استعلام قیمت"),
                            ("availability_inquiry", "استعلام موجودی"),
                            ("product_question", "پرسش درباره محصول"),
                            ("other", "سایر"),
                        ],
                        max_length=50,
                        verbose_name="موضوع درخواست",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="توضیحات"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="خوانده شده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "درخواست تماس",
                "verbose_name_plural": "درخواست\u200cهای تماس",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "created_at"],
                        name="contact_phone_created_idx",
                    ),
                    models.Index(
                        fields=["subject", "created_at"],
                        name="contact_subject_created_idx",
                    ),
                ],
            },
        ),
    ]
