# Generated by Django 5.2 on 2026-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contactrequest",
            name="contact_phone_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactrequest",
            name="contact_subject_created_idx",
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="خوانده شده"),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["phone_number", "-created_at"], name="contact_phone_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["subject", "-created_at"], name="contact_subject_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["is_read", "-created_at"], name="contact_read_created_idx"
            ),
        ),
    ]
