# Generated by Django 5.2 on 2026-09-01 18:24

import utils.upload
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.upload.upload_to,
                validators=[utils.validators.validate_image],
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=180,
                unique=True,
                verbose_name="اسلاگ",
            ),
        ),
    ]
